sudo: required
services:
  - docker

before_install:
  - docker build -t mic3ael/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run mic3ael/react-test npm test  -- --coverage

after_success:
  - docker build -t mic3ael/multi-client ./client
  - docker build -t mic3ael/multi-nginx ./nginx
  - docker build -t mic3ael/multi-server ./server
  - docker build -t mic3ael/multi-worker ./worker

  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

# Take those images and push them to docker hub
  - docker push mic3ael/multi-client
  - docker push mic3ael/multi-nginx
  - docker push mic3ael/multi-server
  - docker push mic3ael/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-525707720621
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
