sudo: required
services:
  - docker

before_install:
  - docker build -t mic3ael/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run mic3ael/react-test npm test  -- --coverage

after_success:
  - docker build -t mic3ael/multi-client ./client
  - docker build -t mic3ael/multi-nginx ./nginx
  - docker build -t mic3ael/multi-server ./server
  - docker build -t mic3ael/multi-worker ./worker
# Log in to the docker CLI

# Take those images and push them to docker hub